theme = "slick"
icons = "awesome"

[[block]]
block = "cpu"
interval = 1
format = "{utilization}"

[[block]]
block = "temperature"
collapsed = true
interval = 10
format = "{min}/{max}/{average}"
chip = "coretemp-isa-0000"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
format = "{path} {available}"
info_type = "available"
unit = "GB"
interval = 20
warning = 10.0
alert = 5.0

[[block]]
block = "disk_space"
format = "{path} {available}"
path = "/home"
alias = "/home"
info_type = "available"
interval = 20
warning = 10.0
alert = 5.0

#[[block]]
#block = "disk_space"
#path = "/home/ow/2nd-ssd"
#alias = "/2"
#info_type = "available"
#unit = "GB"
#interval = 20
#warning = 20.0
#alert = 10.0

[[block]]
block = "disk_space"
format = "{path} {available}"
path = "/tmp"
alias = "/tmp"
info_type = "available"
unit = "GB"
interval = 20
warning = 7.0
alert = 3.0


[[block]]
block = "net"
device = "wlp3s0"
format = "{speed_up}{speed_down}"
#ssid = true
#signal_strength =false 
#ip = false
#speed_up = true 
#graph_up = false 
interval = 5

[[block]]
block = "networkmanager"
on_click = "alacritty -e nmtui"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+", "virbr0"]
interface_name_include = []
ap_format = "{ssid^10} {strength}"

[[block]]
block = "custom"
command = "timeout .5 dig +short myip.opendns.com @resolver1.opendns.com"
#command = "echo ext. `curl -4 icanhazip.com`"
interval = 10

[[block]]
block = "docker"
interval = 2
format = "{running}/{total}"

[[block]]
block = "sound"

[[block]]
block = "keyboard_layout"
driver = "setxkbmap"
interval = 15

[[block]]
block = "battery"
driver = "upower"
format = "{percentage} {time} {power}"

[[block]]
block = "time"
interval = 5
format = "%d/%m %T"

[[block]]
block = "toggle"
text = ""
command_state = "xrandr | grep DP3-1\\ connected\\ 38 | grep -v eDP1"
command_on = "~/.screenlayout/dock.sh"
command_off = "~/.screenlayout/single.sh"
interval = 5
